// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn46SShPVltpChAlzgoZEpjlyxDiGFGaE',
    appId: '1:33448064440:web:f407345f926f6d41604b4d',
    messagingSenderId: '33448064440',
    projectId: 'mynotes-flutter-project-ce377',
    authDomain: 'mynotes-flutter-project-ce377.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-ce377.firebasestorage.app',
    measurementId: 'G-5M4SFTWF5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6N0lG1PVepzNR3OH4gl_bEr7Xaekopk',
    appId: '1:33448064440:android:61cb4ca7cb84a739604b4d',
    messagingSenderId: '33448064440',
    projectId: 'mynotes-flutter-project-ce377',
    storageBucket: 'mynotes-flutter-project-ce377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG0qaHoueSkQzpDaCwI3N1ykSVqUjtn6s',
    appId: '1:33448064440:ios:a413799f6020ace7604b4d',
    messagingSenderId: '33448064440',
    projectId: 'mynotes-flutter-project-ce377',
    storageBucket: 'mynotes-flutter-project-ce377.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG0qaHoueSkQzpDaCwI3N1ykSVqUjtn6s',
    appId: '1:33448064440:ios:a413799f6020ace7604b4d',
    messagingSenderId: '33448064440',
    projectId: 'mynotes-flutter-project-ce377',
    storageBucket: 'mynotes-flutter-project-ce377.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn46SShPVltpChAlzgoZEpjlyxDiGFGaE',
    appId: '1:33448064440:web:8fec4ed7ce1d2c46604b4d',
    messagingSenderId: '33448064440',
    projectId: 'mynotes-flutter-project-ce377',
    authDomain: 'mynotes-flutter-project-ce377.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-ce377.firebasestorage.app',
    measurementId: 'G-4G0TNSY7Z1',
  );
}
